package text

import "github.com/aleferri/casmeleon/pkg/text"

//KEYWORDS
const (
	KEYWORD_IF = text.LAST_RESERVED_TOKEN + iota
	KEYWORD_ELSE
	KEYWORD_OPCODE
	KEYWORD_WITH
	KEYWORD_NUM
	KEYWORD_SET
	KEYWORD_UNARY_OP
	KEYWORD_BINARY_OP
	KEYWORD_OUT
	KEYWORD_EXPR
	KEYWORD_ERROR
	KEYWORD_WARNING
	KEYWORD_INLINE
	DOUBLE_CURLY_OPEN
	DOUBLE_CURLY_CLOSE
	ARROW
)
